name: publican
version: 0.1.1
description: The package that will help you out with Dart's Pub
homepage: https://github.com/leocavalcante/publican
authors:
  - Leo Cavalcante <lc@leocavalcante.com>

dependencies:
  args: ^1.4.1

executables:
  publican:

environment:
  sdk: ">=1.19.0 <2.0.0"
